version: 2
jobs:
  build1:
    docker:
       - image: circleci/ruby:2.4.1
    steps:
       - checkout
       - run: echo "Hello there!"
  build2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Good Bye"
workflows:
  version: 2
  CircleciTesting:
    jobs:
      - build1
      - build2