version: 2
jobs:
  build:
    docker:
       - image: circleci/node:8.9
    steps:
       - checkout
       - run: echo "npm installing"
       - run: npm install
       - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Testing starts"
      - run: npm install
      - run: npm test
  mustcompletejob:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "This must complete then test job will run"
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - mustcompletejob
      - test:
          requires:
            - mustcompletejob